import type { CloudflareWorkersAIClient, HermesModelProvider } from "@hermes-os/shared";
import type { MemoryService } from "@hermes-os/memory";
import type { AssistantStateRepository, OpenLoopsRepository, RisksRepository, SourceItemsRepository, TasksRepository } from "@hermes-os/context-graph";
import type { ContextGraphService } from "@hermes-os/context-graph";
import type { ConnectorHub } from "@hermes-os/connectors";
import type { ActivityMonitor } from "@hermes-os/audit-log";
import type { AuditLogger } from "@hermes-os/audit-log";
import type { ProactivityPolicy } from "@hermes-os/policies";
import type { ToolExecutor } from "@hermes-os/tool-executor";
import type { ToolRegistry } from "@hermes-os/tool-executor";
import { ResearchAgent } from "./research-agent.js";
import { MemoryAgent } from "./memory-agent.js";
import { ChiefOfStaffAgent } from "./chief-of-staff-agent.js";
import { RiskPredictionAgent } from "./risk-prediction-agent.js";
import { CodingAgent } from "./coding-agent.js";
import { BrowserAgent } from "./browser-agent.js";
import { LaptopControlAgent } from "./laptop-control-agent.js";
import { WritingAgent } from "./writing-agent.js";
import { GeneralAgent } from "./general-agent.js";
import { AutonomousAgent } from "./autonomous-agent.js";
import { DigitalPresenceMonitor } from "./digital-presence-monitor.js";
export type AgentRuntime = {
    research: ResearchAgent | null;
    memory: MemoryAgent;
    chiefOfStaff: ChiefOfStaffAgent;
    risk: RiskPredictionAgent;
    autonomous: AutonomousAgent | null;
    presence: DigitalPresenceMonitor;
    coding: CodingAgent;
    browser: BrowserAgent;
    laptop: LaptopControlAgent;
    writing: WritingAgent;
    general: GeneralAgent;
    hermes: HermesModelProvider | null;
    cloudflare: CloudflareWorkersAIClient | null;
};
export declare function createAgentRuntime(deps: {
    cloudflare: CloudflareWorkersAIClient | null;
    hermes: HermesModelProvider | null;
    memory: MemoryService;
    executor: ToolExecutor;
    registry: ToolRegistry;
    workspaceRoot: string;
    tasks: TasksRepository;
    openLoops: OpenLoopsRepository;
    sourceItems: SourceItemsRepository;
    risks: RisksRepository;
    stateRepo: AssistantStateRepository;
    proactivity: ProactivityPolicy;
    connectorHub: ConnectorHub | null;
    contextGraph?: ContextGraphService;
    audit: AuditLogger;
    activity: ActivityMonitor;
}): AgentRuntime;
//# sourceMappingURL=agent-runtime.d.ts.map