export {
  buildResearchFollowUpPrompt,
  createResearchSession,
  handleStructuredFollowUp,
  hasValidStructuredRecommendation,
  isCheaperFollowUp,
  isNewProductQuestion,
  isProductExplanationFollowUp,
  isPurchaseLinkFollowUp,
  isResearchFollowUpMessage,
  isStructuredProductFollowUp,
  normalizeSession,
  shouldHandleWithProductFlow,
  isProductClarificationReply,
  shouldHandleWithResearchFlow,
  wantsOpenPurchaseInBrowser,
  wantsExplicitMemoryUse,
  pickPurchaseLink,
  type ResearchSession,
} from "./research-session.js";
